### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by ajaywazir** [swissembedded/em#2]
Hi
How do I contact you regarding EMDO101

Ajay
Enrochem Pte. Ltd
Singapore

**Comment by eduardojoseramos** [comment]
Hi Ajay!
my email is eduardojoseramos@hotmail.com and my skype is eduardojoseramos
my UTC time is -4h

**Comment by swissembedded** [comment]
Hi Ajay,
you can drop me email daniel.haensse @ swissembedded dot com
Best Dani

**Comment by eduardojoseramos** [comment]
Hi Daniel!
yes Ajay, you can contact directly to Daniel who is the owner Project

**Comment by ajaywazir** [comment]
HI Daniel,
I have sent email via official email a/wazir/enrochem/com
please confirm if received

Ajay
